- server/src/main/java/com/mainproject/server/dateNotice/controller/DateNoticeController.java
- server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticeSimpleResponseDto.java
- server/src/main/java/com/mainproject/server/dto/PageResponseDto.java
- server/src/main/java/com/mainproject/server/image/controller/ImageController.java
- server/src/main/java/com/mainproject/server/message/controller/MessageController.java
- server/src/main/java/com/mainproject/server/profile/controller/ProfileController.java
- server/src/main/java/com/mainproject/server/profile/dto/ProfileListResponseDto.java
- server/src/main/java/com/mainproject/server/profile/dto/ProfilePageDto.java
- server/src/main/java/com/mainproject/server/profile/dto/ProfileResponseDto.java
- server/src/main/java/com/mainproject/server/profile/dto/ProfileSimpleResponseDto.java
- server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
- server/src/main/java/com/mainproject/server/tutoring/dto/TutoringDto.java
- server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPatchDto.java
- server/src/main/java/com/mainproject/server/tutoring/dto/TutoringResponseDto.java
- server/src/main/java/com/mainproject/server/tutoring/dto/TutoringSimpleResponseDto.java
- server/src/main/java/com/mainproject/server/user/controller/UserController.java
- server/src/main/java/com/mainproject/server/utils/StubData.java
> BE: Sutb Controller 리팩토링

- server/src/main/java/com/mainproject/server/auth/handler/UserAuthenticationSuccessHandler.java
- server/src/main/java/com/mainproject/server/auth/oauth2/OAuth2UserSuccessHandler.java
- server/src/main/java/com/mainproject/server/auth/oauth2/service/CustomOAuth2UserService.java
- server/src/main/java/com/mainproject/server/config/SecurityConfig.java
- server/src/main/java/com/mainproject/server/constant/ProfileStatus.java
- server/src/main/java/com/mainproject/server/dto/AuthSuccessTokenResponseDto.java
- server/src/main/java/com/mainproject/server/profile/dto/ProfileSimpleResponseDto.java
- server/src/main/java/com/mainproject/server/utils/StubData.java
- 로그인 후 응답 데이터 수정
- User Select 쿼리문 최적화를 위해 Success Handler로 OAuth2 유저 생성 로직 이동
> feat: OAuth2 Success Handler 구현 및 로그인 후 응답 데이터 수정

- client/src/components/Button.jsx
- client/src/components/Message/Chat.jsx
- client/src/components/Message/MessageContent.jsx
- client/src/components/Message/MessageContent.module.css
- client/src/components/Message/MessageList.jsx
- client/src/components/Message/MessageList.module.css
- client/src/components/Modal.jsx
- client/src/components/Modal.module.css
- client/src/pages/Message.jsx
- client/src/pages/Message.module.css
- client/src/pages/ModalTestPage.jsx
일부 기능은 구현되지 않았으며, 차후 API 작성 완료 후 추가 개발 예정입니다.
> feat: Message 페이지 생성

- client/src/components/Header.jsx
- client/src/components/TutoringList/Tutoring.jsx
- client/src/components/TutoringList/Tutoring.module.css
- client/src/pages/TutoringList.jsx
- client/src/pages/TutoringList.module.css
일부 구현되지 않은 API 관련 기능은 제외하고 구현되었습니다. 해당 부분은 주석처리하여 구분해두었습니다.
> feat: TutorlingList 페이지 작성

- server/src/main/java/com/mainproject/server/auth/token/JwtTokenizer.java
- server/src/main/java/com/mainproject/server/config/SecurityConfig.java
- server/src/main/java/com/mainproject/server/dateNotice/dto/DateNoticePatchDto.java
- server/src/main/java/com/mainproject/server/dateNotice/dto/HomeworkPatchDto.java
- server/src/main/java/com/mainproject/server/dateNotice/entity/DateNotice.java
- server/src/main/java/com/mainproject/server/dateNotice/entity/Homework.java
- server/src/main/java/com/mainproject/server/dateNotice/repository/HomeworkRepository.java
- server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
- server/src/main/java/com/mainproject/server/image/service/ImageService.java
- server/src/main/java/com/mainproject/server/message/entity/Message.java
- server/src/main/java/com/mainproject/server/message/entity/MessageRoom.java
- server/src/main/java/com/mainproject/server/message/service/MessageService.java
- server/src/main/java/com/mainproject/server/profile/entity/Profile.java
- server/src/main/java/com/mainproject/server/profile/repository/custom/CustomProfileRepositoryImpl.java
- server/src/main/java/com/mainproject/server/tutoring/dto/TutoringDto.java
- server/src/main/java/com/mainproject/server/tutoring/dto/TutoringResponseDto.java
- server/src/main/java/com/mainproject/server/tutoring/entity/Tutoring.java
- server/src/main/java/com/mainproject/server/user/controller/UserController.java
- server/src/main/java/com/mainproject/server/user/service/UserService.java
- server/src/main/resources/application.yml
- server/src/main/resources/data.sql
- 메세지 룸 삭제시 연관 관계 문제로 Error Fix
- Security 권한 필요 API 설정
- DateNotice DB 저장시 컬럼 NULL 방지 유효성 검증 추가
- DateNotice Patch 메소드 수정 
- Image 삭제시 기본 이미지로 대체 되도록 수정
- 튜터/튜티 파라미터 없이 검색 가능하도록 수정
- 회원 정보 수정 시 회원의 상태 코드별 분기하여 수정 할 수 있도록 반영 
- Tutoring 상세 조회 요청 데이터 필드 추가
> Be/refactor : Security 적용 및 리팩토링

- server/src/main/java/com/mainproject/server/audit/Auditable.java
- server/src/main/java/com/mainproject/server/profile/controller/ProfileController.java
- server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
- server/src/main/java/com/mainproject/server/user/controller/UserController.java
- server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
- server/src/test/java/com/mainproject/server/profile/service/ProfileServiceTest.java
- 타임 스탬프 필드 Setter 추가
- 튜터/튜티 리스트 조회 시 Default Sort 기준 변경 createAt -> updateAt
- Profile Service 코드 중복 제거 및 불필요한 Repository 호출 코드 제거
- 프로필 서비스 로직 테스트 코드 작성
> Be/test: 프로필 서비스 로직 테스트 코드 작성 및 리팩토링

- server/src/main/java/com/mainproject/server/dto/PageResponseDto.java
- 기존 페이지 요청 시작 0 응답 페이지 1
- 변경 페이지 요청 시작 0 응답 페이지 0
> fix: Page Response Page Number 수정

- server/src/main/java/com/mainproject/server/dateNotice/service/DateNoticeService.java
- server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
- server/src/main/java/com/mainproject/server/utils/StubData.java
- server/src/test/java/com/mainproject/server/dateNotice/service/DateNoticeServiceTest.java
- server/src/test/java/com/mainproject/server/profile/service/ProfileServiceTest.java
- server/src/test/java/com/mainproject/server/tutoring/service/TutoringServiceTest.java
> Be/test 과외 일지 서비스 테스트 코드 작성

- server/src/main/java/com/mainproject/server/review/service/ReviewService.java
- server/src/main/java/com/mainproject/server/utils/StubData.java
- server/src/test/java/com/mainproject/server/review/service/ReviewServiceTest.java
> Be/test : 후기 서비스 로직 테스트 코드 작성

- server/src/main/java/com/mainproject/server/auth/redis/dto/RefreshDto.java
- server/src/main/java/com/mainproject/server/auth/token/JwtTokenizer.java
- server/src/main/java/com/mainproject/server/subject/service/SubjectService.java
- server/src/test/java/com/mainproject/server/auth/token/JwtTokenizerTest.java
> Be/test: JwtTokenizer 테스트 코드 작성

- server/src/docs/asciidoc/index.adoc
- server/src/main/java/com/mainproject/server/auth/controller/AuthController.java
- server/src/main/java/com/mainproject/server/auth/dto/PasswordDto.java
- server/src/main/java/com/mainproject/server/dto/ErrorResponse.java
- server/src/main/java/com/mainproject/server/user/controller/UserController.java
- server/src/main/java/com/mainproject/server/user/dto/UserPatchDto.java
- server/src/main/java/com/mainproject/server/user/dto/UserPostDto.java
- server/src/main/java/com/mainproject/server/user/service/UserService.java
- server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
- server/src/main/java/com/mainproject/server/utils/StubData.java
- server/src/test/java/com/mainproject/server/user/controller/UserControllerTest.java
- server/src/test/java/com/mainproject/server/user/service/UserServiceTest.java
> Be/test: 회원 컨트롤러 테스트 작성 

- server/src/docs/asciidoc/index.adoc
- server/src/main/java/com/mainproject/server/auth/dto/PasswordDto.java
- server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
- server/src/main/resources/static/docs/index.html
- server/src/test/java/com/mainproject/server/user/controller/UserControllerTest.java
- User 컨트롤러 벨리데이션 누락부 수정
- User 컨트롤러 테스트 코드 작성
- StubData 수정 
- Rest Docs 반영
> Be/test: 회원 컨트롤러 테스트 코드 작성 및 리팩토링

- server/src/docs/asciidoc/index.adoc
- server/src/main/java/com/mainproject/server/config/SecurityConfig.java
> Be/fix: Security 수정 / CORS ISSUE

- server/src/main/java/com/mainproject/server/review/controller/ReviewController.java
- server/src/main/java/com/mainproject/server/review/service/ReviewService.java
- server/src/main/java/com/mainproject/server/tutoring/controller/TutoringController.java
- server/src/main/java/com/mainproject/server/tutoring/dto/TutoringDto.java
- server/src/main/java/com/mainproject/server/tutoring/dto/TutoringPatchDto.java
- server/src/main/java/com/mainproject/server/tutoring/dto/TutoringResponseDto.java
- server/src/main/java/com/mainproject/server/tutoring/mapper/TutoringMapper.java
- server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
- Tutoring 상세 조회시 Review ID 필드 추가
- Tutoring 상세 조회 시 일지 페이지 네이션 고정 사이즈 변경
- 기타 오타 수정 및 수정 부분 반영
> Be/refactor: Tutoring & Review 응답 필드 추가

- server/src/main/java/com/mainproject/server/message/dto/MessageRoomResponseDto.java
- server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
- Tutoring 조회시 프로필 접근 권한 유효성 검증 추가
- Tutoring Patch 시 UNCHECK 상태일 경우 Patch 가능하도록 유효성 검증 수정
- MessageRoom Response Tutoring ID 데이터 필드 추가
Issue #165
> Be/refactor Tutoring & MessageRoom

- server/src/main/java/com/mainproject/server/message/dto/MessageRoomSimpleResponseDto.java
> refactor: Message Room Response SenderId 필드 추가

- client/src/components/ChangeProfile/ChangeProfileCard.jsx
- client/src/components/MainSection/LoginForm.jsx
- client/src/components/Tutoring/FinishedJournalList.jsx
- client/src/components/Tutoring/FinishedJournalList.module.css
- client/src/components/Tutoring/JournalList.jsx
- client/src/components/Tutoring/JournalList.module.css
- client/src/components/Tutoring/Journals.jsx
- client/src/components/modal/AdminModal.module.css
- client/src/components/modal/ReviewModal.module.css
- client/src/pages/Tutoring.jsx
- fix: 후기 모달 textArea 크기 수정 불가능하게 변경
- fix: 리뷰 추가/수정 시 backdrop 동작 안하게 수정
- fix: 데이터 받아올 때 생기는 잔상 문제 해결
- fix: 이미지 수정 후 페이지 리다이렉트 시 이미지 반영 안되는 문제 해결
- fix: 잔상 이슈 일부 해결 및 최근 공지 링크 이슈 해결
- feat: 소셜 로그인 API 추가
> fix: 각종 issue 해결 #178

- server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
- server/src/main/java/com/mainproject/server/auth/oauth2/provider/CustomOAuth2Provider.java
> refactor: CORS Custom Filter & OAuth2 Redirect Url 수정

- server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
- server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
- server/src/main/java/com/mainproject/server/auth/oauth2/OAuth2UserSuccessHandler.java
> be/refactor: OAuth2 로그인 후 인증 되지 않는 문제 확인하기 위하여 Log 추가

- server/src/main/java/com/mainproject/server/auth/oauth2/OAuth2UserSuccessHandler.java
> chore: OAuth2 로그인 후 토큰 발급시 Bearer 누락

- server/src/main/java/com/mainproject/server/message/entity/Message.java
- server/src/main/java/com/mainproject/server/message/service/MessageService.java
- server/src/test/java/com/mainproject/server/message/MessageServiceTest.java
- Message Service Test Code 리팩토링
Issue #112
> test: Message Service Test Code Refactor

- server/src/docs/asciidoc/index.adoc
- server/src/main/java/com/mainproject/server/message/controller/MessageController.java
- server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
- server/src/test/java/com/mainproject/server/message/controller/MessageControllerTest.java
- Message 도메인 관련 로직 리팩토링
- Message Controller 유효성 검증 누락 추가
- Message Contorller 테스트 코드 작성
- Rest Docs 반영 
Issue #197
> Be/test: 메세지 컨트롤러 테스트 코드 작성 및 REST Docs 반영

- server/src/main/java/com/mainproject/server/message/service/MessageService.java
- server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
> refactor: Tutoring 종료 시 Message Room의 tutoringId 삭제 하도록 수정

- server/src/main/java/com/mainproject/server/auth/details/UserCustomDetailsService.java
- server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
- server/src/main/java/com/mainproject/server/auth/handler/UserAuthenticationFailureHandler.java
> refactor: 일반 및 소셜 로그인 시 비활성 회원 예외 처리

- server/src/main/java/com/mainproject/server/config/SecurityConfig.java
- server/src/main/java/com/mainproject/server/constant/ProfileStatus.java
- server/src/main/java/com/mainproject/server/profile/controller/ProfileController.java
- server/src/main/java/com/mainproject/server/profile/service/ProfileService.java
> Be: 프로필 삭제 시 DB 데이터 삭제하지 않고 비활성화 상태값 수정으로 로직 변경

- server/src/test/java/com/mainproject/server/profile/service/ProfileServiceTest.java
> test: 프로필 서비스 로직 변경사항 테스트 코드 반영

- server/src/main/java/com/mainproject/server/message/dto/MessageRoomQueryDto.java
- server/src/main/java/com/mainproject/server/message/dto/MessageRoomSimpleResponseDto.java
- server/src/main/java/com/mainproject/server/message/entity/MessageRoom.java
- server/src/main/java/com/mainproject/server/message/repository/MessageRoomRepository.java
- server/src/main/java/com/mainproject/server/message/repository/custom/CustomMessageRoomRepository.java
- server/src/main/java/com/mainproject/server/message/repository/custom/CustomMessageRoomRepositoryImpl.java
- server/src/main/java/com/mainproject/server/message/service/MessageService.java
- server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
- server/src/test/java/com/mainproject/server/message/MessageServiceTest.java
> Be/refactor: 특정 프로필 메세지 룸 리스트 조회 쿼리 리팩토링

- client/src/components/Button.jsx
- client/src/components/Button.module.css
- client/src/components/MainSection/UserInfoForm.jsx
- client/src/components/MainSection/UserInfoForm.module.css
- client/src/components/profileSection/MyProfileCard.jsx
- client/src/components/profileSection/MyProfileCard.module.css
- client/src/components/profileSection/ProfileCard.jsx
- client/src/components/profileSection/ProfileCard.module.css
- client/src/components/profileSection/ProfileContents.module.css
- client/src/components/profileSection/Toggle.module.css
- client/src/pages/Admin.module.css
- client/src/pages/MyProfile.module.css
- client/src/pages/TuteeProfile.module.css
- client/src/pages/TutorProfile.module.css
- client/src/pages/UserInfo.module.css
- feat: 프로필 모바일 뷰포트 적용 
- fix: top 버튼 모바일 뷰포트 크기 수정
- feat: 마이 프로필 모바일 뷰포트 적용 
- feat: 회원 정보 수정 페이지 모바일 뷰포트 스타일 적용
- feat: 전체 프로필 관리 페이지 모바일 뷰포트 적용
> feat: 모바일 뷰포트 수정

- server/src/main/java/com/mainproject/server/tutoring/repository/custom/CustomTutoringRepository.java
- server/src/main/java/com/mainproject/server/tutoring/repository/custom/CustomTutoringRepositoryImpl.java
- server/src/main/java/com/mainproject/server/tutoring/service/TutoringService.java
- server/src/test/java/com/mainproject/server/tutoring/service/TutoringServiceTest.java
- 과외 상세 조회 시 불필요한 요청 쿼리 한방 쿼리로 조회 하도록 Repository 구현
- 성능 테스트 진행하여 약 60% 개선 효과 확인
Issue #262
> Be/refactor: 과외 상세 조회 쿼리 성능 개선

- client/src/App.jsx
- client/src/util/ScrollToTop.jsx
다른 페이지로 이동할 경우 스크롤을 페이지의 최상단으로 이동하도록 함 
util 폴더에 ScrollToTop 컴포넌트 생성 
App.jsx 에 ScrollToTop 컴포넌트 적용
> feat: Scroll Restoration

- server/build.gradle
- server/src/main/java/com/mainproject/server/alarm/entity/Alarm.java
- server/src/main/java/com/mainproject/server/auth/filter/CorsFilter.java
- server/src/main/java/com/mainproject/server/auth/token/JwtTokenizer.java
- server/src/main/java/com/mainproject/server/config/RedisConfig.java
- server/src/main/java/com/mainproject/server/config/SecurityConfig.java
- server/src/main/java/com/mainproject/server/config/WebSocketConfig.java
- server/src/main/java/com/mainproject/server/config/handler/WebSocketHandler.java
- server/src/main/java/com/mainproject/server/message/controller/MessageController.java
- server/src/main/java/com/mainproject/server/message/dto/MessageResponseDto.java
- server/src/main/java/com/mainproject/server/message/service/MessageService.java
- server/src/main/java/com/mainproject/server/message/ui/RedisPublisher.java
- server/src/main/java/com/mainproject/server/message/ui/RedisSubscriber.java
- server/src/main/java/com/mainproject/server/utils/ResponseStubData.java
- server/src/test/java/com/mainproject/server/message/controller/MessageControllerTest.java
> BE/Refactor: Websocket Message 구현

- server/src/test/java/com/mainproject/server/tutoring/service/TutoringServiceTest.java
> test: Alarm 기능 추가 Test 코드 반영

- server/src/main/java/com/mainproject/server/alarm/entity/Alarm.java
> fix: Alarm Enum 필드 String 타입으로 수정

- server/src/main/java/com/mainproject/server/alarm/controller/AlarmController.java
- server/src/main/java/com/mainproject/server/alarm/service/AlarmService.java
- Alarm Controller 오타 수정
- Alarm All Patch ConcurrentModificationException 수정
Issue #276
> Be/fix 알림 기능 에러 및 오타 수정

- client/src/components/Message/Chat.module.css
- client/src/components/Message/MessageContent.jsx
- client/src/components/Message/MessageContent.module.css
- client/src/components/Message/MessageList.module.css
- client/src/pages/Message.module.css
- client/src/util/useLiveChat.js
- 아이폰 사파리 뷰포트 이슈
- 웹소켓 에러 이슈
- message key props 오류
- 기타 스타일 수정
> FE / fix: message 관련 오류 및 이슈 해결

- client/src/components/Message/MessageContent.jsx
- client/src/components/Message/MessageContent.module.css
[fix: 모바일 전송 버튼 클릭 시 키보드 사라짐 해결](https://github.com/codestates-seb/seb41_main_003/commit/df7d51d4bb25a19632f78d589f61567d3365368c)
[design: 스크롤바 사이즈 변경](https://github.com/codestates-seb/seb41_main_003/commit/bea32cae0f9d03a7cd56d9123f3abc6ab73f97a6)
[fix: 아이폰 사파리 텍스트 입력 이슈 해결](https://github.com/codestates-seb/seb41_main_003/commit/a7efcb71141053262de64750878fa2c1e0236fe3)
> FE / fix: 모바일 뷰포트 추가 이슈 해결
